#!/usr/bin/env python3
"""[livingworld] Regenerates src/.../livingworld/plan/Cells.java from the mod's multi-block contracts.
usage: gen_cells.py <built mod jar> <repo>"""
import json, zipfile, re, sys, os
J, R = sys.argv[1], sys.argv[2]
z = zipfile.ZipFile(J)
out = ['package com.formaworks.frontierhunts.livingworld.plan;', '',
       "/** [livingworld] Cell layouts (north-facing, relative to the multi-block origin) of the mod's multi-block field gear,",
       ' * copied from the block contracts (data/frontierhunts/compact_tents/*.json, TowerBlindShapeData). Generated by',
       " * tools/livingworld/gen_cells.py; the cell index is the block's PART value. */", 'public final class Cells {', '   private Cells() {', '   }', '']
for d in ['backpacker_dome_tent', 'hunters_canvas_tent', 'solo_ridge_tent']:
    c = json.loads(z.read(f'data/frontierhunts/compact_tents/{d}.json'))
    name = d.upper()
    out.append(f'   public static final int[][] {name} = {{' + ','.join('{%d,%d,%d}' % tuple(p) for p in c['cells']) + '};')
    out.append(f'   public static final int {name}_BED = {c["bed"]};')
src = open('/home/claude/fh/dec62g8/com/formaworks/frontierhunts/expedition/TowerBlindShapeData.java').read()
m = re.search(r'PARTS = new int\[\]\[\]\{(.*?)\};', src, re.S)
parts = re.findall(r'\{(-?\d+), (-?\d+), (-?\d+)\}', m.group(1))
out.append('   public static final int[][] TOWER_BLIND = {' + ','.join('{%s,%s,%s}' % p for p in parts) + '};')
out.append('}')
open(os.path.join(R, 'src/com/formaworks/frontierhunts/livingworld/plan/Cells.java'), 'w').write('\n'.join(out) + '\n')
