package com.formaworks.frontierhunts.wildlife2026.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** GENERATED by animals/gen.py - vanilla-style box models for the Frontier wildlife (do not edit by hand). */
public final class WildlifeModels {
   private WildlifeModels() {
   }

   public static LayerDefinition create(String id) {
      return switch (id) {
         case "wolf" -> wolf();
         case "coyote" -> coyote();
         case "cougar" -> cougar();
         case "grizzly" -> grizzly();
         case "black_bear" -> black_bear();
         case "polar_bear" -> polar_bear();
         case "bison" -> bison();
         case "boar" -> boar();
         case "pronghorn" -> pronghorn();
         case "grouse" -> grouse();
         case "duck" -> duck();
         case "lion" -> lion();
         case "panther" -> panther();
         case "cheetah" -> cheetah();
         default -> throw new IllegalArgumentException(id);
      };
   }

   /** Animation metadata: kind (0 quadruped, 1 bird), rest drop px, tail base xRot, flags. */
   public static float[] meta(String id) {
      return switch (id) {
         case "wolf" -> new float[]{0, 7.0F, 0.75F, 0, 0, 0.0F, 0};
         case "coyote" -> new float[]{0, 7.0F, 0.55F, 0, 0, 0.0F, 0};
         case "cougar" -> new float[]{0, 8.0F, 0.4F, 0, 0, 0.0F, 0};
         case "grizzly" -> new float[]{0, 8.0F, 0.6F, 1, 0, 0.0F, 0};
         case "black_bear" -> new float[]{0, 7.0F, 0.6F, 1, 0, 0.0F, 0};
         case "polar_bear" -> new float[]{0, 8.0F, 0.6F, 1, 0, 0.0F, 0};
         case "bison" -> new float[]{0, 8.0F, 0.3F, 1, 0, 0.15F, 0};
         case "boar" -> new float[]{0, 5.0F, 0.4F, 0, 0, 0.0F, 0};
         case "pronghorn" -> new float[]{0, 9.0F, 0.5F, 0, 1, 0.0F, 0};
         case "grouse" -> new float[]{1, 3.0F, -1.0F, 0, 0, 0.0F, 0};
         case "duck" -> new float[]{1, 3.0F, 0.0F, 0, 0, 0.0F, 1};
         case "lion" -> new float[]{0, 8.0F, 0.5F, 0, 0, 0.0F, 0};
         case "panther" -> new float[]{0, 7.0F, 0.9F, 0, 0, 0.0F, 0};
         case "cheetah" -> new float[]{0, 9.0F, 0.4F, 0, 0, 0.0F, 0};
         default -> new float[]{0, 6, 0, 0, 0, 0, 0};
      };
   }

   private static LayerDefinition wolf() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -7.0F, -8.0F, 8.0F, 8.0F, 16.0F).texOffs(0, 24).addBox(-4.5F, -8.0F, -8.5F, 9.0F, 9.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(32, 24).addBox(-3.5F, -4.0F, -6.0F, 7.0F, 7.0F, 6.0F).texOffs(0, 53).addBox(-2.0F, 0.0F, -10.0F, 4.0F, 3.0F, 4.0F).texOffs(16, 53).addBox(-3.5F, -7.0F, -3.0F, 2.0F, 3.0F, 1.0F).texOffs(22, 53).addBox(1.5F, -7.0F, -3.0F, 2.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -5.0F, -8.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(12, 40).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(-2.5F, 15.0F, -5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(24, 40).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(2.5F, 15.0F, -5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(36, 40).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(-2.5F, 15.0F, 5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(48, 40).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(2.5F, 15.0F, 5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 40).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 10.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -6.0F, 8.0F, 0.75F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64);
   }

   private static LayerDefinition coyote() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -6.0F, -7.0F, 6.0F, 7.0F, 14.0F), PartPose.offsetAndRotation(0.0F, 15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(24, 21).addBox(-3.0F, -4.0F, -5.0F, 6.0F, 5.0F, 5.0F).texOffs(46, 21).addBox(-1.5F, -1.0F, -9.0F, 3.0F, 2.0F, 4.0F).texOffs(0, 32).addBox(-3.0F, -8.0F, -2.0F, 2.0F, 4.0F, 1.0F).texOffs(6, 32).addBox(1.0F, -8.0F, -2.0F, 2.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -4.0F, -7.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(52, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(-1.8F, 15.0F, -5.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(0, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(1.8F, 15.0F, -5.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(8, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(-1.8F, 15.0F, 5.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(16, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(1.8F, 15.0F, 5.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(40, 0).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -5.0F, 7.0F, 0.55F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64);
   }

   private static LayerDefinition cougar() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -7.0F, -10.0F, 8.0F, 8.0F, 20.0F), PartPose.offsetAndRotation(0.0F, 14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 46).addBox(-3.0F, -4.0F, -5.0F, 6.0F, 6.0F, 5.0F).texOffs(22, 46).addBox(-2.0F, -1.0F, -7.0F, 4.0F, 3.0F, 2.0F).texOffs(34, 46).addBox(-3.0F, -6.0F, -2.0F, 2.0F, 2.0F, 1.0F).texOffs(40, 46).addBox(1.0F, -6.0F, -2.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -5.0F, -10.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(12, 28).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 10.0F, 3.0F), PartPose.offsetAndRotation(-2.5F, 14.0F, -7.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(24, 28).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 10.0F, 3.0F), PartPose.offsetAndRotation(2.5F, 14.0F, -7.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(36, 28).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 10.0F, 3.0F), PartPose.offsetAndRotation(-2.5F, 14.0F, 7.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(48, 28).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 10.0F, 3.0F), PartPose.offsetAndRotation(2.5F, 14.0F, 7.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 28).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 15.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -6.0F, 10.0F, 0.4F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64);
   }

   private static LayerDefinition grizzly() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-7.0F, -10.0F, -12.0F, 14.0F, 12.0F, 24.0F).texOffs(76, 36).addBox(-6.0F, -13.0F, -11.0F, 12.0F, 4.0F, 9.0F), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(44, 36).addBox(-4.5F, -4.0F, -7.0F, 9.0F, 8.0F, 7.0F).texOffs(0, 53).addBox(-2.5F, 0.0F, -11.0F, 5.0F, 4.0F, 4.0F).texOffs(26, 53).addBox(-4.5F, -6.0F, -3.0F, 2.0F, 2.0F, 1.0F).texOffs(32, 53).addBox(2.5F, -6.0F, -3.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -6.0F, -12.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(76, 0).addBox(-2.5F, 0.0F, -3.0F, 5.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(-4.5F, 13.0F, -8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(98, 0).addBox(-2.5F, 0.0F, -3.0F, 5.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(4.5F, 13.0F, -8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(0, 36).addBox(-2.5F, 0.0F, -3.0F, 5.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(-4.5F, 13.0F, 8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(22, 36).addBox(-2.5F, 0.0F, -3.0F, 5.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(4.5F, 13.0F, 8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(18, 53).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -8.0F, 12.0F, 0.6F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 128, 64);
   }

   private static LayerDefinition black_bear() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-5.5F, -9.0F, -10.0F, 11.0F, 10.0F, 20.0F), PartPose.offsetAndRotation(0.0F, 14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(18, 45).addBox(-4.0F, -4.0F, -6.0F, 8.0F, 7.0F, 6.0F).texOffs(46, 45).addBox(-2.0F, 0.0F, -9.0F, 4.0F, 3.0F, 3.0F).texOffs(8, 60).addBox(-4.0F, -6.0F, -2.0F, 2.0F, 2.0F, 1.0F).texOffs(14, 60).addBox(2.0F, -6.0F, -2.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -5.0F, -10.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(0, 30).addBox(-2.0F, 0.0F, -2.5F, 4.0F, 10.0F, 5.0F), PartPose.offsetAndRotation(-3.5F, 14.0F, -6.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(18, 30).addBox(-2.0F, 0.0F, -2.5F, 4.0F, 10.0F, 5.0F), PartPose.offsetAndRotation(3.5F, 14.0F, -6.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(36, 30).addBox(-2.0F, 0.0F, -2.5F, 4.0F, 10.0F, 5.0F), PartPose.offsetAndRotation(-3.5F, 14.0F, 6.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(0, 45).addBox(-2.0F, 0.0F, -2.5F, 4.0F, 10.0F, 5.0F), PartPose.offsetAndRotation(3.5F, 14.0F, 6.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 60).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -7.0F, 10.0F, 0.6F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64);
   }

   private static LayerDefinition polar_bear() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-7.5F, -11.0F, -13.0F, 15.0F, 13.0F, 26.0F), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(104, 39).addBox(-3.5F, -3.0F, -4.0F, 7.0F, 7.0F, 5.0F).texOffs(72, 39).addBox(-4.5F, -4.0F, -10.0F, 9.0F, 8.0F, 7.0F).texOffs(0, 57).addBox(-2.5F, 0.0F, -14.0F, 5.0F, 4.0F, 4.0F).texOffs(26, 57).addBox(-4.5F, -6.0F, -5.0F, 2.0F, 2.0F, 1.0F).texOffs(32, 57).addBox(2.5F, -6.0F, -5.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -6.0F, -13.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(82, 0).addBox(-2.5F, 0.0F, -3.5F, 5.0F, 11.0F, 7.0F), PartPose.offsetAndRotation(-4.5F, 13.0F, -9.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(0, 39).addBox(-2.5F, 0.0F, -3.5F, 5.0F, 11.0F, 7.0F), PartPose.offsetAndRotation(4.5F, 13.0F, -9.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(24, 39).addBox(-2.5F, 0.0F, -3.5F, 5.0F, 11.0F, 7.0F), PartPose.offsetAndRotation(-4.5F, 13.0F, 9.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(48, 39).addBox(-2.5F, 0.0F, -3.5F, 5.0F, 11.0F, 7.0F), PartPose.offsetAndRotation(4.5F, 13.0F, 9.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(18, 57).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -9.0F, 13.0F, 0.6F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 128, 128);
   }

   private static LayerDefinition bison() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 31).addBox(-6.0F, -10.0F, 0.0F, 12.0F, 11.0F, 12.0F).texOffs(0, 0).addBox(-8.0F, -15.0F, -13.0F, 16.0F, 17.0F, 14.0F).texOffs(0, 88).addBox(-6.0F, -18.0F, -11.0F, 12.0F, 4.0F, 9.0F).texOffs(0, 101).addBox(-7.0F, 2.0F, -12.0F, 14.0F, 3.0F, 10.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 54).addBox(-4.5F, 0.0F, -8.0F, 9.0F, 10.0F, 8.0F).texOffs(20, 114).addBox(-3.5F, 5.0F, -11.0F, 7.0F, 5.0F, 3.0F).texOffs(0, 114).addBox(-2.5F, 10.0F, -8.0F, 5.0F, 4.0F, 5.0F).texOffs(48, 114).addBox(-7.5F, 0.0F, -6.0F, 3.0F, 2.0F, 2.0F).texOffs(0, 123).addBox(4.5F, 0.0F, -6.0F, 3.0F, 2.0F, 2.0F).texOffs(10, 123).addBox(-7.5F, -2.0F, -6.0F, 2.0F, 2.0F, 2.0F).texOffs(18, 123).addBox(5.5F, -2.0F, -6.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -6.0F, -13.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(34, 54).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(-4.0F, 12.0F, -8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(0, 72).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(4.0F, 12.0F, -8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(16, 72).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(-3.5F, 12.0F, 8.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(32, 72).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(3.5F, 12.0F, 8.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(48, 101).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F).texOffs(40, 114).addBox(-1.0F, 8.0F, -1.0F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -8.0F, 12.0F, 0.3F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 128);
   }

   private static LayerDefinition boar() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-5.0F, -9.0F, -9.0F, 10.0F, 10.0F, 18.0F).texOffs(0, 42).addBox(-5.5F, -11.0F, -9.5F, 11.0F, 4.0F, 9.0F).texOffs(40, 42).addBox(-1.0F, -13.0F, -9.0F, 2.0F, 2.0F, 8.0F).texOffs(0, 65).addBox(-1.0F, -11.0F, -1.0F, 2.0F, 2.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 17.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 28).addBox(-4.0F, -3.0F, -7.0F, 8.0F, 7.0F, 7.0F).texOffs(18, 65).addBox(-2.5F, 0.0F, -11.0F, 5.0F, 4.0F, 4.0F).texOffs(40, 65).addBox(-3.5F, -0.5F, -10.5F, 1.0F, 3.0F, 1.0F).texOffs(44, 65).addBox(2.5F, -0.5F, -10.5F, 1.0F, 3.0F, 1.0F).texOffs(48, 65).addBox(-4.0F, -6.0F, -2.0F, 2.0F, 3.0F, 1.0F).texOffs(54, 65).addBox(2.0F, -6.0F, -2.0F, 2.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -6.0F, -9.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(0, 55).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 7.0F, 3.0F), PartPose.offsetAndRotation(-3.0F, 17.0F, -6.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(12, 55).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 7.0F, 3.0F), PartPose.offsetAndRotation(3.0F, 17.0F, -6.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(24, 55).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 7.0F, 3.0F), PartPose.offsetAndRotation(-3.0F, 17.0F, 6.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(36, 55).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 7.0F, 3.0F), PartPose.offsetAndRotation(3.0F, 17.0F, 6.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(36, 65).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -7.0F, 9.0F, 0.4F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 128);
   }

   private static LayerDefinition pronghorn() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -6.0F, -7.0F, 7.0F, 7.0F, 14.0F), PartPose.offsetAndRotation(0.0F, 11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition neck = body.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(16, 21).addBox(-1.5F, -9.0F, -1.5F, 3.0F, 10.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -4.0F, -6.0F, 0.25F, 0.0F, 0.0F));
      PartDefinition head = neck.addOrReplaceChild("head", CubeListBuilder.create().texOffs(28, 21).addBox(-2.0F, -3.0F, -5.0F, 4.0F, 4.0F, 6.0F).texOffs(48, 21).addBox(-2.0F, -7.0F, -1.0F, 1.0F, 4.0F, 1.0F).texOffs(52, 21).addBox(1.0F, -7.0F, -1.0F, 1.0F, 4.0F, 1.0F).texOffs(6, 36).addBox(-2.0F, -5.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(10, 36).addBox(1.0F, -5.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(56, 21).addBox(-2.8F, -4.0F, 0.0F, 1.0F, 2.0F, 1.0F).texOffs(60, 21).addBox(1.8F, -4.0F, 0.0F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -8.0F, -0.5F, -0.25F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(42, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 13.0F, 2.0F), PartPose.offsetAndRotation(-2.2F, 11.0F, -5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(50, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 13.0F, 2.0F), PartPose.offsetAndRotation(2.2F, 11.0F, -5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(0, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 13.0F, 2.0F), PartPose.offsetAndRotation(-2.2F, 11.0F, 5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(8, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 13.0F, 2.0F), PartPose.offsetAndRotation(2.2F, 11.0F, 5.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 36).addBox(-1.0F, 0.0F, -0.5F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -5.0F, 7.0F, 0.5F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64);
   }

   private static LayerDefinition grouse() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.5F, -4.0F, -4.0F, 5.0F, 5.0F, 8.0F).texOffs(32, 13).addBox(-2.0F, -4.5F, -4.0F, 4.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 19.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 13).addBox(-1.5F, -3.0F, -2.0F, 3.0F, 3.0F, 3.0F).texOffs(50, 13).addBox(-0.5F, -2.0F, -3.0F, 1.0F, 1.0F, 1.0F).texOffs(44, 13).addBox(-0.5F, -4.0F, -1.0F, 1.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -3.0F, -3.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition wing_l = body.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(26, 0).addBox(-1.0F, 0.0F, -3.0F, 1.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(-2.5F, -3.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition wing_r = body.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(40, 0).addBox(0.0F, 0.0F, -3.0F, 1.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(2.5F, -3.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      // [wingshot] the hand: primaries beyond the wrist, folded away when the wing is closed
      wing_l.addOrReplaceChild("wing_l_tip", CubeListBuilder.create().texOffs(0, 32).addBox(-1.0F, 0.0F, -2.5F, 1.0F, 5.0F, 5.0F), PartPose.offset(-0.01F, 4.0F, 0.3F));
      wing_r.addOrReplaceChild("wing_r_tip", CubeListBuilder.create().texOffs(16, 32).addBox(0.0F, 0.0F, -2.5F, 1.0F, 5.0F, 5.0F), PartPose.offset(0.01F, 4.0F, 0.3F));
      PartDefinition leg_l = root.addOrReplaceChild("leg_l", CubeListBuilder.create().texOffs(24, 13).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(-1.0F, 20.0F, 0.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_r = root.addOrReplaceChild("leg_r", CubeListBuilder.create().texOffs(28, 13).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(1.0F, 20.0F, 0.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(12, 13).addBox(-2.5F, -5.0F, 0.0F, 5.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -3.0F, 3.5F, -1.0F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64); // [wingshot] 64x64: the wing hands live in the lower half
   }

   private static LayerDefinition duck() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -4.0F, -4.5F, 6.0F, 5.0F, 9.0F).texOffs(24, 14).addBox(-2.0F, -3.0F, 4.5F, 4.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 19.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(16, 14).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(0, 14).addBox(-2.0F, -7.0F, -3.0F, 4.0F, 4.0F, 4.0F).texOffs(36, 14).addBox(-1.5F, -5.0F, -6.0F, 3.0F, 1.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -3.0F, -3.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition wing_l = body.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(30, 0).addBox(-1.0F, 0.0F, 0.0F, 1.0F, 4.0F, 7.0F), PartPose.offsetAndRotation(-3.0F, -3.5F, -2.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition wing_r = body.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(46, 0).addBox(0.0F, 0.0F, 0.0F, 1.0F, 4.0F, 7.0F), PartPose.offsetAndRotation(3.0F, -3.5F, -2.0F, 0.0F, 0.0F, 0.0F));
      // [wingshot] the hand: long pointed primaries beyond the wrist, folded away when the wing is closed
      wing_l.addOrReplaceChild("wing_l_tip", CubeListBuilder.create().texOffs(0, 32).addBox(-1.0F, 0.0F, 0.0F, 1.0F, 6.0F, 6.0F), PartPose.offset(-0.01F, 4.0F, 0.4F));
      wing_r.addOrReplaceChild("wing_r_tip", CubeListBuilder.create().texOffs(16, 32).addBox(0.0F, 0.0F, 0.0F, 1.0F, 6.0F, 6.0F), PartPose.offset(0.01F, 4.0F, 0.4F));
      PartDefinition leg_l = root.addOrReplaceChild("leg_l", CubeListBuilder.create().texOffs(48, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F).texOffs(56, 14).addBox(-1.0F, 3.0F, -1.5F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(-1.5F, 20.0F, 0.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_r = root.addOrReplaceChild("leg_r", CubeListBuilder.create().texOffs(52, 14).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F).texOffs(0, 22).addBox(-1.0F, 3.0F, -1.5F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(1.5F, 20.0F, 0.5F, 0.0F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64); // [wingshot] 64x64: the wing hands live in the lower half
   }

   private static LayerDefinition lion() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5F, -8.0F, -11.0F, 9.0F, 9.0F, 22.0F).texOffs(0, 49).addBox(-5.0F, -8.5F, -11.5F, 10.0F, 10.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(32, 65).addBox(-3.5F, -4.0F, -6.0F, 7.0F, 7.0F, 6.0F).texOffs(12, 80).addBox(-2.0F, 0.0F, -8.0F, 4.0F, 3.0F, 2.0F).texOffs(0, 31).addBox(-5.5F, -7.0F, -4.0F, 11.0F, 12.0F, 6.0F), PartPose.offsetAndRotation(0.0F, -5.0F, -11.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(32, 49).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 11.0F, 4.0F), PartPose.offsetAndRotation(-3.0F, 13.0F, -8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(48, 49).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 11.0F, 4.0F), PartPose.offsetAndRotation(3.0F, 13.0F, -8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(0, 65).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 11.0F, 4.0F), PartPose.offsetAndRotation(-3.0F, 13.0F, 8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(16, 65).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 11.0F, 4.0F), PartPose.offsetAndRotation(3.0F, 13.0F, 8.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(34, 31).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 15.0F, 2.0F).texOffs(0, 80).addBox(-1.5F, 14.0F, -1.5F, 3.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -7.0F, 11.0F, 0.5F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 128);
   }

   private static LayerDefinition panther() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -6.0F, -10.0F, 7.0F, 7.0F, 20.0F), PartPose.offsetAndRotation(0.0F, 15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 39).addBox(-3.0F, -3.0F, -5.0F, 6.0F, 5.0F, 5.0F).texOffs(30, 39).addBox(-1.5F, 0.0F, -7.0F, 3.0F, 2.0F, 2.0F).texOffs(40, 39).addBox(-3.0F, -5.0F, -2.0F, 2.0F, 2.0F, 1.0F).texOffs(46, 39).addBox(1.0F, -5.0F, -2.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -4.0F, -10.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(0, 27).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(-2.3F, 15.0F, -7.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(12, 27).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(2.3F, 15.0F, -7.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(24, 27).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(-2.3F, 15.0F, 7.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(36, 27).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 9.0F, 3.0F), PartPose.offsetAndRotation(2.3F, 15.0F, 7.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(48, 27).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -5.0F, 10.0F, 0.9F, 0.0F, 0.0F));
      PartDefinition tail_tip = tail.addOrReplaceChild("tail_tip", CubeListBuilder.create().texOffs(22, 39).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 6.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 9.0F, 0.0F, 1.25F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64);
   }

   private static LayerDefinition cheetah() {
      MeshDefinition mesh = new MeshDefinition();
      PartDefinition base = mesh.getRoot();
      PartDefinition root = base.addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -6.0F, -8.5F, 6.0F, 7.0F, 17.0F).texOffs(0, 24).addBox(-3.5F, -6.5F, -9.0F, 7.0F, 9.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(8, 40).addBox(-2.5F, -3.0F, -4.0F, 5.0F, 4.0F, 4.0F).texOffs(26, 40).addBox(-1.5F, 0.0F, -6.0F, 3.0F, 2.0F, 2.0F).texOffs(36, 40).addBox(-2.5F, -4.0F, -1.0F, 1.0F, 1.0F, 1.0F).texOffs(40, 40).addBox(1.5F, -4.0F, -1.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -5.0F, -9.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fl = root.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(36, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F), PartPose.offsetAndRotation(-2.0F, 12.0F, -6.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_fr = root.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(44, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 12.0F, -6.0F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_bl = root.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(52, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F), PartPose.offsetAndRotation(-2.0F, 12.0F, 6.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition leg_br = root.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(0, 40).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 12.0F, 6.5F, 0.0F, 0.0F, 0.0F));
      PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(28, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 14.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -5.0F, 8.5F, 0.4F, 0.0F, 0.0F));
      return LayerDefinition.create(mesh, 64, 64);
   }

}
