package com.formaworks.frontierhunts.vital;

import com.formaworks.frontierhunts.hunting.ArrowTip;
import com.formaworks.frontierhunts.hunting.DeerAnatomy;
import com.formaworks.frontierhunts.tracking.BloodTrail.BloodType;
import com.formaworks.frontierhunts.wildlife2026.WildlifeMob;
import com.formaworks.frontierhunts.wildlife2026.WildlifeSpecies;
import net.minecraft.world.phys.Vec3;

/**
 * [vital] Shot-placement anatomy for the 2026 wildlife. Every species gets a torso (from its box-model proportions,
 * scaled to the live hitbox) with a heart low in the chest right behind the front leg, two lung lobes above and behind
 * it, the liver behind the diaphragm, the gut filling the rear belly, plus a head, a neck and leg columns. A projectile
 * hit is classified by tracing its actual line of flight through that body in the animal's rotated (and bedded) body
 * frame, up to the depth its energy can reach. Birds: the body core (heart and lungs) is the vital zone.
 * <p>
 * Pure geometry: no world access, so the kill cam predictor can run it on a future impact.
 */
public final class WildlifeVitals {
   private WildlifeVitals() {
   }

   /** Where the shot went, most severe first. */
   public enum Zone {
      HEART(9, true),
      DOUBLE_LUNG(8, true),
      LUNG(7, true),
      HEAD(6, false),
      NECK(5, false),
      LIVER(4, false),
      GUT(3, false),
      FLESH(2, false),
      LEG(1, false),
      GRAZE(0, false);

      public final int severity;
      /** heart / lung: the animal drops on the spot (given a lethal tip and enough energy) */
      public final boolean vital;

      Zone(int severity, boolean vital) {
         this.severity = severity;
         this.vital = vital;
      }

      /** a wound that kills after a run (bleeding out) if it doesn't drop the animal */
      public boolean fatal() {
         return this.severity >= GUT.severity;
      }

      public BloodType blood() {
         return switch (this) {
            case HEART -> BloodType.HEART;
            case DOUBLE_LUNG, LUNG -> BloodType.LUNG;
            case HEAD, NECK -> BloodType.ARTERIAL;
            case LIVER -> BloodType.LIVER;
            case GUT -> BloodType.GUT;
            default -> BloodType.MUSCLE;
         };
      }

      /** the deer region with the same meaning (kill cam card) */
      public DeerAnatomy.Region region() {
         return switch (this) {
            case HEART -> DeerAnatomy.Region.HEART;
            case DOUBLE_LUNG -> DeerAnatomy.Region.DOUBLE_LUNG;
            case LUNG -> DeerAnatomy.Region.LUNG;
            case HEAD -> DeerAnatomy.Region.HEAD;
            case NECK -> DeerAnatomy.Region.NECK;
            case LIVER -> DeerAnatomy.Region.LIVER;
            case GUT -> DeerAnatomy.Region.GUT;
            case LEG -> DeerAnatomy.Region.LEG;
            default -> DeerAnatomy.Region.BODY;
         };
      }

      /** the most this hit may take off in one go when it does not drop the animal (fraction of max health) */
      float impactShare() {
         return switch (this) {
            case HEART, DOUBLE_LUNG, LUNG -> 0.45F; // only reached by a too-weak / non-lethal-tip hit
            case HEAD, NECK -> 0.4F;
            case LIVER -> 0.35F;
            case GUT -> 0.25F;
            case FLESH -> 0.3F;
            case LEG -> 0.25F;
            case GRAZE -> 0.12F;
         };
      }
   }

   /**
    * Torso geometry in blocks (before the entity's own scale): half width, belly and back height (standing), how far the
    * chest reaches forward and the rump back from the entity origin, the front leg (elbow line) position, head centre
    * (forward, height) and radius, and how far the body sinks when bedded.
    * Generated by tools/vital/gen_torso.py from the classic box models x classicScale.
    */
   record Torso(double hw, double bot, double top, double front, double rear, double leg, double headF, double headY, double headR, double drop) {
      double length() {
         return this.front + this.rear;
      }

      double height() {
         return this.top - this.bot;
      }
   }

   static Torso torso(WildlifeSpecies s) {
      return switch (s) {
         case WOLF -> new Torso(0.254, 0.452, 0.961, 0.481, 0.452, 0.311, 0.650, 0.820, 0.198, 0.396);
         case COYOTE -> new Torso(0.171, 0.457, 0.857, 0.400, 0.400, 0.286, 0.543, 0.829, 0.171, 0.400);
         case COUGAR -> new Torso(0.214, 0.482, 0.911, 0.536, 0.536, 0.375, 0.670, 0.857, 0.161, 0.429);
         case GRIZZLY -> new Torso(0.365, 0.469, 1.094, 0.625, 0.625, 0.417, 0.807, 0.885, 0.234, 0.417);
         case BLACK_BEAR -> new Torso(0.278, 0.454, 0.959, 0.505, 0.505, 0.328, 0.656, 0.782, 0.202, 0.353);
         case POLAR_BEAR -> new Torso(0.400, 0.480, 1.173, 0.693, 0.693, 0.480, 0.773, 0.880, 0.187, 0.426);
         case BISON -> new Torso(0.487, 0.609, 1.644, 0.792, 0.731, 0.487, 1.035, 0.792, 0.304, 0.487);
         case BOAR -> new Torso(0.281, 0.338, 0.900, 0.506, 0.506, 0.338, 0.703, 0.703, 0.225, 0.281);
         case PRONGHORN -> new Torso(0.228, 0.780, 1.235, 0.455, 0.455, 0.358, 0.552, 1.690, 0.195, 0.585);
         case GROUSE -> new Torso(0.116, 0.186, 0.419, 0.186, 0.186, -0.023, 0.163, 0.442, 0.070, 0.140);
         case DUCK -> new Torso(0.143, 0.190, 0.427, 0.214, 0.214, -0.024, 0.166, 0.451, 0.071, 0.143);
         case LION -> new Torso(0.290, 0.551, 1.132, 0.667, 0.638, 0.464, 0.813, 0.958, 0.203, 0.464);
         case PANTHER -> new Torso(0.186, 0.425, 0.797, 0.531, 0.531, 0.372, 0.664, 0.717, 0.159, 0.372);
         case CHEETAH -> new Torso(0.208, 0.564, 1.098, 0.534, 0.505, 0.356, 0.653, 1.069, 0.148, 0.534);
         // elk / moose are Whitetail entities (DeerAnatomy); a generic ungulate just in case
         default -> new Torso(0.30, 0.95, 1.55, 0.60, 0.60, 0.42, 0.90, 1.85, 0.22, 0.60);
      };
   }

   /** Result of one classified hit. {@code entry} is in world space (null if the line never touched the body). */
   public record Hit(Zone zone, Vec3 entry, float energy, boolean lethalTip) {
      /** heart / lung hit with a lethal point and enough energy: drops on the spot, kill cam */
      public boolean drops() {
         return this.zone.vital && this.lethalTip && this.energy >= ShotVitals.MIN_VITAL_ENERGY;
      }
   }

   /** Classifies a projectile flying along {@code dir} through {@code point} (any point on its line near the animal). */
   public static Hit classify(WildlifeMob mob, Vec3 point, Vec3 dir, float energy, ArrowTip tip) {
      boolean lethalTip = tip == null || tip.lethal;
      float scale = Math.max(0.2F, mob.getScale());
      boolean bedded = mob.legsFolded() && mob.onGround();
      return classify(mob.species, mob.position(), mob.yBodyRot, scale, bedded, point, dir, energy, lethalTip);
   }

   /** Entity-free core (also used by the offline harness). */
   public static Hit classify(WildlifeSpecies species, Vec3 origin, float bodyYaw, float scale, boolean bedded, Vec3 point, Vec3 dir,
                              float energy, boolean lethalTip) {
      // [bugs] reject anything that is not a sane, finite line near a sane, finite animal (NaN / Infinity / absurd
      // coordinates from a broken projectile or another mod would otherwise poison the march below)
      if (species == null || origin == null || point == null || dir == null) {
         return new Hit(Zone.GRAZE, null, energy, lethalTip);
      }
      if (!finite(point) || !finite(origin) || !finite(dir) || !Float.isFinite(bodyYaw) || !Float.isFinite(energy)
         || !(scale > 0.0F) || !Float.isFinite(scale)) {
         return new Hit(Zone.GRAZE, null, Float.isFinite(energy) ? energy : 0.0F, lethalTip);
      }
      double dl = dir.lengthSqr();
      if (!Double.isFinite(dl) || dl < 1.0E-10) {
         return new Hit(Zone.GRAZE, null, energy, lethalTip);
      }
      scale = Math.clamp(scale, 0.05F, 64.0F);
      Torso t = torso(species);
      Vec3 d = dir.normalize();
      double yaw = Math.toRadians(bodyYaw);
      // body frame: f = towards the head, s = to the animal's side, y = up from its feet; in torso units (/scale)
      double fx = -Math.sin(yaw), fz = Math.cos(yaw);
      double sx = Math.cos(yaw), sz = Math.sin(yaw);
      double drop = bedded ? t.drop() : 0.0;
      Vec3 rel = point.subtract(origin);
      double pf = (rel.x * fx + rel.z * fz) / scale, ps = (rel.x * sx + rel.z * sz) / scale, py = rel.y / scale + drop;
      double df = d.x * fx + d.z * fz, ds = d.x * sx + d.z * sz, dy = d.y;
      // march the line across the whole animal (both directions from the given point)
      double reach = t.length() + t.headR() * 2.0 + 1.5 + Math.abs(t.headF());
      double step = Math.max(0.006, Math.min(t.hw(), t.height() * 0.5) / 14.0);
      double depthLimit = (0.3 + 1.1 * Math.clamp(energy, 0.0F, 1.2F)) / scale; // how far the projectile can drive in
      Zone best = null;
      boolean left = false, right = false;
      double entered = Double.NaN;
      // centre the march on the line's closest approach to the body centre (the given point may be anywhere on the line)
      double k0 = -(pf * df + (py - (t.bot() + t.top()) * 0.5) * dy + ps * ds);
      // [bugs] the line must pass near the body: a point thousands of blocks away (or a non-finite k0) used to make
      // `k += step` underflow (k never changes) and the server tick never ended (watchdog crash). Integer-indexed march
      // with a hard iteration cap, so it always terminates.
      if (!Double.isFinite(k0) || Math.abs(k0) > MAX_LINE_OFFSET || !Double.isFinite(pf + ps + py)) {
         return new Hit(Zone.GRAZE, null, energy, lethalTip);
      }
      int steps = (int)Math.min(MAX_STEPS, Math.ceil(2.0 * reach / step));
      double kStart = k0 - reach;
      for (int i = 0; i <= steps; i++) {
         double k = kStart + i * step;
         double f = pf + df * k, s = ps + ds * k, y = py + dy * k;
         Zone z = zoneAt(species.bird, t, f, y, s);
         if (z == null) {
            continue;
         }
         if (Double.isNaN(entered)) {
            entered = k;
         } else if (k - entered > depthLimit) {
            break;
         }
         if (z == Zone.LUNG) {
            if (s < 0.0) {
               left = true;
            } else {
               right = true;
            }
            if (left && right) {
               z = Zone.DOUBLE_LUNG;
            }
         }
         if (best == null || z.severity > best.severity) {
            best = z;
         }
      }
      if (best == null) {
         // accepted by the hitbox but never touched the body: hair graze
         return new Hit(Zone.GRAZE, null, energy, lethalTip);
      }
      if (!lethalTip && best.severity > Zone.FLESH.severity) {
         best = Zone.FLESH; // blunt / judo point: a bruise, not a wound channel (as Whitetail does)
      }
      Vec3 entry = point.add(d.scale(entered * scale));
      return new Hit(best, finite(entry) ? entry : null, energy, lethalTip);
   }

   /** [bugs] the march only runs on lines within this many torso units of the body centre (the caller passes a point at the hitbox) */
   static final double MAX_LINE_OFFSET = 4096.0;
   /** [bugs] hard cap on march samples (normal shots need ~300-1500) */
   static final int MAX_STEPS = 4096;

   private static boolean finite(Vec3 v) {
      return Double.isFinite(v.x) && Double.isFinite(v.y) && Double.isFinite(v.z);
   }

   /** zone at a body-frame point, or null outside the body */
   static Zone zoneAt(boolean bird, Torso t, double f, double y, double s) {
      double L = t.length(), H = t.height();
      double u = (t.front() - f) / L; // 0 chest front .. 1 rump
      double v = (y - t.bot()) / H; // 0 belly .. 1 back
      double w = s / t.hw(); // -1 .. 1 side to side
      // head (before the torso so a head held low over the chest reads as head)
      double hf = f - t.headF(), hy = y - t.headY();
      if (hf * hf + hy * hy + s * s <= t.headR() * t.headR()) {
         return Zone.HEAD;
      }
      boolean inTorso = u >= 0.0 && u <= 1.0 && v >= 0.0 && v <= 1.0
         && Math.pow(Math.abs(2.0 * v - 1.0), 3.0) + Math.pow(Math.abs(w), 3.0) <= 1.0;
      if (inTorso) {
         if (bird) {
            // body core: heart and lungs sit in the breast, the rest is feathers, wing roots and tail
            return ell(u, v, w, 0.42, 0.5, 0.0, 0.32, 0.42, 0.72) ? Zone.HEART : Zone.FLESH;
         }
         double lu = (t.front() - t.leg()) / L; // elbow line
         if (ell(u, v, w, lu + 0.045, 0.3, 0.0, 0.08, 0.16, 0.42)) {
            return Zone.HEART;
         }
         if (ell(u, v, w, lu + 0.12, 0.58, -0.45, 0.19, 0.3, 0.5) || ell(u, v, w, lu + 0.12, 0.58, 0.45, 0.19, 0.3, 0.5)) {
            return Zone.LUNG; // the caller tells the two lobes apart by side
         }
         if (ell(u, v, w, lu + 0.37, 0.5, 0.0, 0.085, 0.33, 0.8)) {
            return Zone.LIVER;
         }
         if (ell(u, v, w, 0.68, 0.4, 0.0, 0.25, 0.4, 0.92)) {
            return Zone.GUT;
         }
         return Zone.FLESH; // shoulder, brisket, back strap, hindquarter
      }
      if (bird) {
         // wings stick out from the sides, legs below: flesh / leg
         if (u >= -0.05 && u <= 1.1 && v >= 0.1 && v <= 1.0 && Math.abs(w) <= 1.6) {
            return Zone.FLESH;
         }
         if (y >= 0.0 && y < t.bot() && Math.abs(s) < t.hw() * 0.6 && Math.abs(f) < L * 0.2) {
            return Zone.LEG;
         }
         return null;
      }
      // neck: from the chest front up to the head
      if (f > t.front() - 0.05 * L && f < t.headF() && Math.abs(s) < t.hw() * 0.62) {
         double k = Math.clamp((f - t.front()) / Math.max(0.05, t.headF() - t.front()), 0.0, 1.0);
         double cy = t.top() - H * 0.3 + (t.headY() - (t.top() - H * 0.3)) * k;
         double r = H * 0.3 * (1.0 - k) + t.headR() * 0.7 * k;
         if (Math.abs(y - cy) <= r) {
            return Zone.NECK;
         }
      }
      // legs: columns under the torso at the front leg and hind leg lines
      if (y >= 0.0 && y < t.bot() + H * 0.05 && Math.abs(s) < t.hw() * 0.95) {
         double hind = -(t.rear() - (t.front() - t.leg()));
         double r = Math.max(0.04, L * 0.12);
         if (Math.abs(f - t.leg()) < r || Math.abs(f - hind) < r * 1.15) {
            return Zone.LEG;
         }
      }
      return null;
   }

   private static boolean ell(double u, double v, double w, double cu, double cv, double cw, double ru, double rv, double rw) {
      double a = (u - cu) / ru, b = (v - cv) / rv, c = (w - cw) / rw;
      return a * a + b * b + c * c <= 1.0;
   }
}
