import com.formaworks.frontierhunts.clothing.Scent;
import java.util.Locale;

/**
 * [clothing] Offline table of the one scent function (clothing.Scent.factor, pure form) for typical situations, plus the
 * reach of a downwind whiff for the 2026 wildlife noses (clothing.Noses: winded when plume x factor x nose > 0.40, plume
 * straight downwind = exp(-d / 65)). Exit 1 if a sanity check fails.
 *
 * <pre>
 *   javac -proc:none -cp "$(cat .infra/cp62.txt):/tmp/claude-0/cc-clothing" -d /tmp/claude-0/wt tools/clothing/ScentTable.java
 *   java -cp "$(cat .infra/cp62.txt):/tmp/claude-0/cc-clothing:/tmp/claude-0/wt" ScentTable > docs/ws/clothing/scent_table.md
 * </pre>
 */
public final class ScentTable {
   public static void main(String[] a) {
      StringBuilder md = new StringBuilder("# Scent table (generated by tools/clothing/ScentTable.java - do not edit)\n\n");
      md.append("`factor` multiplies the scent plume every animal smells (1.00 = plain clothes). Carbon effectiveness = sum of worn ")
         .append("pieces' share x (0.25 + 0.75 x charge): hood .20, top .45, trousers .35, suit 1.\n\n");
      md.append("| situation | carbon | motion | sweat | wet | spray left | factor | less scent |\n|---|---|---|---|---|---|---|---|\n");
      Object[][] rows = {
         {"Plain clothes, still", 0.0, 1.0, 0.0, 0.0, 0.0},
         {"Plain clothes, sprinting, sweating hard", 0.0, Scent.SPRINT, 0.8, 0.0, 0.0},
         {"Plain clothes, fresh scent-cover spray", 0.0, 1.0, 0.0, 0.0, 1.0},
         {"Carbon jacket only (fresh), still", 0.45, 1.0, 0.0, 0.0, 0.0},
         {"Carbon hood + jacket + trousers (fresh), still", 1.0, 1.0, 0.0, 0.0, 0.0},
         {"Full carbon (fresh), still, fresh spray", 1.0, 1.0, 0.0, 0.0, 1.0},
         {"Full carbon (fresh), spray half gone", 1.0, 1.0, 0.0, 0.0, 0.5},
         {"Full carbon (fresh), walking", 1.0, Scent.WALK, 0.0, 0.0, 0.0},
         {"Full carbon (fresh), sneaking", 1.0, Scent.SNEAK_WALK, 0.0, 0.0, 0.0},
         {"Full carbon (fresh), sprinting, soaked in sweat", 1.0, Scent.SPRINT, 0.8, 0.0, 0.0},
         {"Full carbon (fresh), still, clothes soaked", 1.0, 1.0, 0.0, 1.0, 0.0},
         {"Full carbon, charge 50%, still", 0.25 + 0.75 * 0.5, 1.0, 0.0, 0.0, 0.0},
         {"Full carbon, spent (charge 0), still", 0.25, 1.0, 0.0, 0.0, 0.0},
      };
      double still = 0, fresh = 0, sprint = 0, partial = 0, spent = 0, plainSweat = 0, spray = 0;
      for (int i = 0; i < rows.length; i++) {
         Object[] r = rows[i];
         double f = Scent.factor((double) r[1], (double) r[2], (double) r[3], (double) r[4], (double) r[5], 1.0);
         md.append(String.format(Locale.ROOT, "| %s | %.2f | %.2f | %.0f%% | %.0f%% | %.0f%% | %.3f | %.0f%% |\n", r[0], (double) r[1], (double) r[2],
            (double) r[3] * 100, (double) r[4] * 100, (double) r[5] * 100, f, (1 - Math.min(1, f)) * 100));
         switch (i) {
            case 0 -> still = f;
            case 1 -> plainSweat = f;
            case 3 -> partial = f;
            case 4 -> fresh = f;
            case 5 -> spray = f;
            case 9 -> sprint = f;
            case 12 -> spent = f;
            default -> {
            }
         }
      }
      md.append("\n## Downwind reach of the 2026 wildlife (straight downwind, blocks)\n\n| nose | plain clothes | full carbon, still | full carbon, sprinting + sweat |\n|---|---|---|---|\n");
      String[] names = {"bears 1.6", "wolf 1.4", "coyote, boar 1.3", "elk, moose 1.15", "bison 1.0", "cougar, pronghorn 0.8", "big cats 0.7"};
      double[] noses = {1.6, 1.4, 1.3, 1.15, 1.0, 0.8, 0.7};
      for (int i = 0; i < noses.length; i++) {
         md.append("| ").append(names[i]).append(" | ").append(reach(noses[i], still)).append(" | ").append(reach(noses[i], fresh)).append(" | ")
            .append(reach(noses[i], sprint)).append(" |\n");
      }
      StringBuilder fail = new StringBuilder();
      if (!(fresh >= 0.10 && fresh <= 0.15)) fail.append("- full fresh carbon should cut 85-90% (factor ").append(fresh).append(")\n");
      if (!(partial > fresh && partial < still)) fail.append("- one piece gives part of the effect\n");
      if (!(spray < fresh && spray > Scent.MIN)) fail.append("- the spray stacks on carbon but never reaches zero\n");
      if (!(sprint > 0.6)) fail.append("- sprinting in sweat ruins most of the carbon\n");
      if (!(spent > fresh && spent < still)) fail.append("- spent carbon still helps a little\n");
      if (!(plainSweat > still)) fail.append("- sweat makes a plain hunter smellier\n");
      md.append("\n## Sanity checks\n\n").append(fail.length() == 0
         ? "All pass: full fresh carbon cuts 85-90%, a single piece part of it, the spray stacks (never zero), sweat and sprinting undo most of it, spent carbon still helps a little.\n"
         : "FAILED:\n" + fail);
      System.out.print(md);
      System.exit(fail.length() == 0 ? 0 : 1);
   }

   static String reach(double nose, double factor) {
      // plume x factor x nose > 0.40, plume = exp(-d / 65); capped at the 48-block search radius
      double v = 0.40 / (factor * nose);
      if (v >= 1.0) {
         return "never";
      }
      double d = -65.0 * Math.log(v);
      return d >= 48.0 ? "48 (search radius)" : String.format(Locale.ROOT, "%.0f", d);
   }
}
