package com.formaworks.frontierhunts.livingworld.plan;

/**
 * [livingworld] Block-entity / entity data with translatable text. All flavour text lives in the language file
 * (keys {@code frontierhunts.lw.*}, generated by tools/livingworld/lang.py), so signs, notes and books show in the
 * reader's language.
 */
public final class Text {
   private Text() {
   }

   public static String key(String group, int line) {
      return "frontierhunts.lw." + group + "." + line;
   }

   static String json(String key) {
      return key == null || key.isEmpty() ? "'\"\"'" : "'{\"translate\":\"" + key + "\"}'";
   }

   /** sign block entity data: up to four translated lines from {@code group}.1 .. {@code group}.n, waxed */
   public static String sign(String group, int lines, String color, boolean glow) {
      StringBuilder m = new StringBuilder();
      for (int i = 1; i <= 4; i++) {
         if (i > 1) {
            m.append(',');
         }
         m.append(json(i <= lines ? key(group, i) : null));
      }
      return "{front_text:{messages:[" + m + "],color:\"" + color + "\",has_glowing_text:" + (glow ? "1b" : "0b")
         + "},back_text:{messages:['\"\"','\"\"','\"\"','\"\"'],color:\"black\",has_glowing_text:0b},is_waxed:1b}";
   }

   /** a written book item (SNBT) with translated pages {@code group}.1 .. n and a translated name */
   public static String book(String group, int pages, String title, String author) {
      StringBuilder p = new StringBuilder();
      for (int i = 1; i <= pages; i++) {
         if (i > 1) {
            p.append(',');
         }
         p.append(json(key(group, i)));
      }
      return "{id:\"minecraft:written_book\",count:1,components:{\"minecraft:written_book_content\":{title:\"" + title + "\",author:\"" + author
         + "\",pages:[" + p + "],resolved:1b},\"minecraft:custom_name\":'{\"translate\":\"" + "frontierhunts.lw." + group + ".title\",\"italic\":false}'}}";
   }

   /** a paper note item (SNBT): translated name {@code group}.title and lore lines {@code group}.1 .. n */
   public static String note(String group, int lines) {
      StringBuilder l = new StringBuilder();
      for (int i = 1; i <= lines; i++) {
         if (i > 1) {
            l.append(',');
         }
         l.append("'{\"translate\":\"" + key(group, i) + "\",\"italic\":true,\"color\":\"gray\"}'");
      }
      return "{id:\"minecraft:paper\",count:1,components:{\"minecraft:custom_name\":'{\"translate\":\"frontierhunts.lw." + group
         + ".title\",\"italic\":false}',\"minecraft:lore\":[" + l + "]}}";
   }
}
